[build]
  publish = "public"
  command = "npx tailwindcss -i ./public/input.css -o ./public/output.css --minify"

[[redirects]]
  from = "/*"
  to = "/homepage.html"
  status = 200
  conditions = {path = "/"}

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404